### ISSUE TITLE
Status cycles between ready and "waiting for kubernetes"

### ISSUE THREAD

**Issue by marcoceppi** [juju-solutions/layer-canal#10]
Despite the fact the cluster works as expected, conjure-up can get stuck - and it just looks broken.

**Comment by johnsca** [comment]
It looks like this would be caused by a `CalledProcessError` from `kubectl` in the charm.  @marcoceppi Do you have a copy of the unit log, by chance?

**Comment by tvansteenburgh** [comment]
Issue moved to https://bugs.launchpad.net/bugs/1809360.
