### ISSUE TITLE
Don't modify the docker unit file

### ISSUE THREAD

**Issue by g-ramirez** [juju-solutions/layer-canal#20]
Hello,

It appears the canal charm overwrites the proxy settings from the principal units on the docker daemon.

Steps to reproduce:

juju deploy etcd
juju deploy kubernetes-master
juju deploy kubernetes-worker
juju config kubernetes-worker no_proxy=<something> http_proxy=<something> https_proxy=<something>
juju deploy canal
juju add-relation canal etcd
juju add-relation canal kubernetes-master
juju add-relation canal kubernetes-worker

The below logic is already handled by the principal charm, so having it on the subordinate will overwrite its settings:

@when_any('config.changed.http_proxy', 'config.changed.https_proxy',
          'config.changed.no_proxy')
@when('docker.ready')
def proxy_changed():
    '''The proxy information has changed, render templates and restart the
    docker daemon.'''
    recycle_daemon()

https://api.jujucharms.com/charmstore/v5/~containers/canal/archive/reactive/docker.py
https://api.jujucharms.com/charmstore/v5/~containers/kubernetes-worker/archive/reactive/docker.py

Thanks,
Gabe

**Comment by tvansteenburgh** [comment]
Issue moved to https://bugs.launchpad.net/bugs/1809361.
